### DISCUSSION TITLE
"Jagged" text?

### DISCUSSION THREAD

**Discussion by stikosek** [sourcelair/xterm.js#4868] [Q&A] [answered]
Hello everyone!
Today, after updating *xterm* and *xterm-addon-fit* a really weird problem occurred to which i couldn't find an already existing issue/discussion.
I have no idea whats causing it, since downgrading back didn't fix anything.
This is how it looks like: 
![image](https://github.com/xtermjs/xterm.js/assets/62238729/251a115a-3929-462d-a08c-523b6679a6ff)

This is my code, just like the example given by *xterm-addon-fit*.
```js
	async function setup_terminal() {
		terminal = new xterm.Terminal({
			fontSize: 12,
			cursorBlink: false,
			disableStdin: true,
		});
		
		fitAddon = new FitAddon.FitAddon()
		terminal.loadAddon(fitAddon);
		terminal.open(terminalElement);
		fitAddon.fit();
		
		window.onresize = function () {
			fitAddon.fit();
		};
	}
```

This issue persists on a firefox and on a chromium-based browser, so i really don't know what happened (since it worked flawlessly before).
Any help/push to the right direction would be appreciated.

*Note: I tried removing the fit addon all together, and that didn't help so the problem must be with xterm itself or my own stupidity*

**Comment by jerch** [comment]
This looks like an issue with font kerning and the letterspace calculation, assuming youre using the DOM renderer. Can you post the CSS rules for the terminal? Which font is used here, is that a monospace font? Which xterm version is that?

**Reply by stikosek** [reply]
Hello,
Here is my CSS styling, the font (Red Hat Mono) is monospace - but i don't think its even applied.
*This is the container with the terminal element.*
```css
       #terminal {
		grid-area: term !important;
		padding: 15px;
		border-radius: 1rem;
		background-color: black;
		display: grid;
		grid-template-areas:
			'term'
			'exe';
		grid-template-columns: 1fr;
		grid-template-rows: auto auto;
		overflow-x: hidden;
	}
```
*This is the actual terminal element:*
```css
	#terminal_resizer {
		font-family: 'Red Hat Mono', serif !important;
	}
```
*This is the relationship between them.*
![image](https://github.com/xtermjs/xterm.js/assets/62238729/aa620590-9b48-477b-83c9-f87d630b056c)

I am using the latest versions, 5.3.0 for xterm and 0.8.0 for the fit addon.
