### DISCUSSION TITLE
Just started xterm and got two blocking issues, perhaps solvable

### DISCUSSION THREAD

**Discussion by kopax** [sourcelair/xterm.js#5109] [Q&A]
Hi guys, 

I am using `wetty@2.6.0` which under the hood use xterm.js:

```yaml
{
    "xterm": "^5.0.0",
    "xterm-addon-fit": "^0.6.0",
    "xterm-addon-image": "^0.2.0",
    "xterm-addon-web-links": "^0.7.0"
}
```

So far I have only two big issue : 

1. I don´t go into my entrpoint `.bashrc` and cannot load utils from my `$PATH` (ie `~/.local/bin`) 
2. The addon  `xterm-addon-fit` method `fit()` does not resize properly, see [here](https://github.com/butlerx/wetty/blob/main/src/client/wetty/term.ts#L56) code

![image](https://github.com/user-attachments/assets/5f300168-dd1b-4ada-ac3a-235651324b1f)

*I selected the zone where stdout print, so half of the screen is unused, which is big*

Do you guys have a clue if those can be resolved somehow ?
