### ISSUE TITLE
Can't select text inside a terminal

### ISSUE THREAD

**Issue by andfoy** [sourcelair/xterm.js#758]
While testing selection features for [spyder-terminal](https://github.com/spyder-ide/spyder-terminal), we actually found that is not possible to select text displayed inside a xterm container, we actually performed tests on Firefox, Chrome and also Qt Webkit/WebEngine, without any success. We can't use the features implemented on PR #670

We don't know if we are missing some parameter at our xterm initialization routine: [spyder-terminal/server/static/js/main.js](https://github.com/spyder-ide/spyder-terminal/blob/master/spyder_terminal/server/static/js/main.js)

## Details
- Browser and browser version: Firefox 54, Chrome 59
- OS version: Linux 
- xterm.js version: 2.8.0

### Steps to reproduce

1. Try to select text displayed inside a ``.terminal`` container
2.

**Comment by Tyriar** [comment]
Did you fork xterm.css and not update it?

**Comment by andfoy** [comment]
No, actually we're using the release version one

**Comment by andfoy** [comment]
But I've made some style-related modifications:
```css
#terminal-container {
    height:100vh;
    margin:     0px;
    padding:    0px;
    z-index: 255;
}

#terminal-container .terminal {
    background-color: #000;
    color: #fafafa;
    padding: 0px;
    font-family: 'Ubuntu Mono', monospace;
    height:100%;
    font-size: 1em;
    line-height: 1 !important;
}

```

**Comment by Tyriar** [comment]
Does it have these styles?

```css
.terminal .xterm-selection {
    position: absolute;
    top: 0;
    left: 0;
    z-index: 1;
    opacity: 0.3;
    pointer-events: none;
}

.terminal .xterm-selection div {
    position: absolute;
    background-color: #fff;
}
```
