### ISSUE TITLE
Reverse color mode doesn't work when using a light theme

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#759]
Downstream issue: https://github.com/Microsoft/vscode/issues/30024

JS has no knowledge of the background/foreground colors so it just uses `.xterm-bg-color-15` and `.xterm-color-0` for reversed unstyled text which should be the opposite on light themes.

**Comment by Tyriar** [comment]
Currently the default background/foreground is specified in the following CSS:

```css
#terminal-container .terminal {
    background-color: #111;
    color: #fafafa;
}
```
