### ISSUE TITLE
Why are span's display: inline-block?

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#85]
The comment reads:

```css
/**
 * All styled spans inside terminal lines should be inline-blocks,
 * in orde to achieve better height adjustment.
 */
.terminal .xterm-rows span {
	display: inline-block;
}
```

As far as I can see it only messes with how `::selection` works:

![image](https://cloud.githubusercontent.com/assets/2193314/15873027/7718f35c-2cb1-11e6-9cfc-5b7c0cde3b7a.png)

This is with span's display:inline:

![image](https://cloud.githubusercontent.com/assets/2193314/15873039/92263ccc-2cb1-11e6-9dff-bcd5cb3adc86.png)

This is with the `::selection` changes I've made for vscode which are too cumbersome to do without a JS API.
